### ISSUE TITLE
Add validation for blob magic_byte and version

### ISSUE THREAD

**Issue by pyakushin** [qoollo/pearl#120]

**Comment by ikopylov** [comment]
I suggest to panic, when everything is correct except the version. This will prevent the non-updated BLOBs from being moved to the `corrupted` directory after the following request will be merged: https://github.com/qoollo/pearl/pull/98

**Comment by pyakushin** [comment]
@ikopylov I think it's bad behavior. I added special error for this case and check for this when pearl decides wether or not it should move corrupted blobs.
