### ISSUE TITLE
Review and improve locks in `Storage`

### ISSUE THREAD

**Issue by ikopylov** [qoollo/pearl#187]
`RWLock` on `safe` does protect `active_blob` + `blobs` updates inside, so the `write` lock should be acquired only when these 2 fields updating. But if we look at `write_with_optional_meta` function, it is incorrectly acquire `write` lock (https://github.com/qoollo/pearl/blob/master/src/storage/core.rs#L313). It should acquire `read` lock, because it does not update neither `active_blob` nor `blobs` fields.
Same thing here: https://github.com/qoollo/pearl/blob/master/src/storage/core.rs#L890 and here: https://github.com/qoollo/pearl/blob/master/src/storage/core.rs#L912. Probably, there are more places where `write` lock taken incorrectly.

Also, it is strange that `blobs` protected with additional `RWLock`. In every places this lock acquired right after acquire of `RWLock` on `safe`, thus can be removed.

This incorrect locking mechanism results in significant performance degradation

**Comment by idruzhitskiy** [comment]
RwLock on `blobs` can be removed. But lock can't be made `read` in `write_with_optional_meta`, since `blob.write(...)` requires mutable reference (due to index modification). But mutex on `current_offset` can be removed instead.

**Comment by idruzhitskiy** [comment]
Also any redundant `write` acquisition in most cases should be reported by compiler as `redundant mut`.

**Comment by ikopylov** [comment]
Exclusive lock should be as close to actual write to file as possible, so it is better to keep lock on `current_offset` and somehow avoid `write` lock in `write_with_optional_meta`
