### ISSUE TITLE
Compare several hash functions as a replacement for `aHash`

### ISSUE THREAD

**Issue by ikopylov** [qoollo/pearl#295]
1. Compare `aHash` (with default build + with explicitly enabled aes `RUSTFLAGS=-C target-feature=+aes,+ssse3`), `wyhash`, `fxhash`, `CityHash` and `highway` performance. Use `x86_64-unknown-linux-musl` as a target in this comparison
2. Also compare hash quality in the list here: https://github.com/rurban/smhasher
3. Check algorithm and its implementation license (it should be MIT)

Rust crate with some hash functions: https://github.com/flier/rust-fasthash

**Comment by archeoss** [comment]
[comparisons](https://github.com/archeoss/hash-comparison)

**Comment by ikopylov** [comment]
Based on the comparison results, aHash was built into the pearl. Pull request: https://github.com/qoollo/pearl/pull/303
