### ISSUE TITLE
Add API method to get the memory occupied by the index

### ISSUE THREAD

**Issue by ikopylov** [qoollo/pearl#68]

**Comment by Justarone** [comment]
[missed, wrote it into PR]
02.12 - 09.12: 9h (acquaintance with the project + some thoughts about solution realization)
09.12 - 16.12: 3h (first version)

16.12 - 23.12: 1.5h (restructure logic a bit (caching key in header and computing size of header with serialized_size))

**Comment by Justarone** [comment]
26.12 - 27.12: 1.5h (add test for this public method)

**Comment by Justarone** [comment]
28.12: 4h (tests, fixes, description for tests and measurements logic)
