### ISSUE TITLE
Return a special error code from the write method if the physical disk is unavailable

### ISSUE THREAD

**Issue by ikopylov** [qoollo/pearl#77]
Bob needs this to handle a disk failure

**Comment by Justarone** [comment]
04.02 - 2h (experiments with page caching during read, research about errors where device is unmounted and needed part of file is NOT cached)

**Comment by Justarone** [comment]
04.02 - 2h (deliver responsibility for file availablility on blob)

**Comment by Justarone** [comment]
09.02 - 1h (pearl new error refactoring)
